stages:
  - build_and_deploy

build_and_deploy_iam_api:
  stage: build_and_deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SERVER_SSH_PRIVATE" | base64 -d > ~/.ssh/id_rsa_connect
    - sha256sum ~/.ssh/id_rsa_connect
    - chmod 400 ~/.ssh/id_rsa_connect
    - ssh-keyscan "$SERVER_IP" >> ~/.ssh/known_hosts
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t $DOCKER_HUB_USERNAME/sm-erp:iam_api-service .
    - docker push $DOCKER_HUB_USERNAME/sm-erp:iam_api-service
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_connect $SERVER_USERNAME@$SERVER_IP -T "sh deploys/outsource/sm-erp/iam_api-service.deploy.sh"
  only:
    - release
